# Generated by Django 4.2.4 on 2023-08-23 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Batiment',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('heure', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'groupe',
            },
        ),
        migrations.CreateModel(
            name='Heure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Heure',
            },
        ),
        migrations.CreateModel(
            name='Jours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Jour',
            },
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Matiere',
            },
        ),
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Niveau',
            },
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50)),
                ('batiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delta.batiment')),
            ],
            options={
                'verbose_name': 'Salle',
            },
        ),
        migrations.CreateModel(
            name='RunParam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heure', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='delta.heure')),
                ('jours', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='delta.jours')),
                ('niveau', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='delta.niveau')),
            ],
            options={
                'verbose_name': 'RunParam',
            },
        ),
        migrations.CreateModel(
            name='Professeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=5, unique=True)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=100)),
                ('status', models.BooleanField()),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delta.grade')),
                ('groupes', models.ManyToManyField(related_name='professeurs_associes', to='delta.groupe')),
                ('matieres', models.ManyToManyField(related_name='professeurs', to='delta.matiere')),
            ],
            options={
                'verbose_name': 'Professeur',
            },
        ),
        migrations.AddField(
            model_name='matiere',
            name='niveaux',
            field=models.ManyToManyField(related_name='matieres', to='delta.niveau'),
        ),
        migrations.AddField(
            model_name='groupe',
            name='matieres',
            field=models.ManyToManyField(related_name='groupes', to='delta.matiere'),
        ),
        migrations.AddField(
            model_name='groupe',
            name='niveau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delta.niveau'),
        ),
        migrations.AddField(
            model_name='groupe',
            name='professeurs',
            field=models.ManyToManyField(related_name='groupes_associes', to='delta.professeur'),
        ),
        migrations.CreateModel(
            name='Duree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=20)),
                ('matieres', models.ManyToManyField(related_name='durees', to='delta.matiere')),
                ('niveaux', models.ManyToManyField(related_name='durees', to='delta.niveau')),
            ],
            options={
                'verbose_name': 'Duree',
            },
        ),
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50)),
                ('professeurs', models.ManyToManyField(related_name='cycles', to='delta.professeur')),
            ],
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField()),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delta.groupe')),
                ('heure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delta.heure')),
                ('jours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delta.jours')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delta.matiere')),
                ('professeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delta.professeur')),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delta.salle')),
            ],
            options={
                'verbose_name': 'Cour',
            },
        ),
    ]
