# Generated by Django 4.2.4 on 2023-08-20 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delta', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batiment',
            options={'verbose_name': 'Batiment'},
        ),
        migrations.AlterModelOptions(
            name='cours',
            options={'verbose_name': 'Cour'},
        ),
        migrations.AlterModelOptions(
            name='duree',
            options={'verbose_name': 'Durée'},
        ),
        migrations.AlterModelOptions(
            name='groupe',
            options={'verbose_name': 'groupe'},
        ),
        migrations.AlterModelOptions(
            name='heure',
            options={'verbose_name': 'Heure'},
        ),
        migrations.AlterModelOptions(
            name='jours',
            options={'verbose_name': 'Jour'},
        ),
        migrations.AlterModelOptions(
            name='salle',
            options={'verbose_name': 'Salle'},
        ),
        migrations.AddField(
            model_name='grade',
            name='heure',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='status',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='RunParam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heure', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='delta.heure')),
                ('jours', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='delta.jours')),
                ('niveau', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='delta.niveau')),
            ],
        ),
    ]
