# Generated by Django 4.2.4 on 2023-08-20 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delta', '0002_alter_batiment_options_alter_cours_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='duree',
            options={'verbose_name': 'Duree'},
        ),
        migrations.AlterModelOptions(
            name='matiere',
            options={'verbose_name': 'Matiere'},
        ),
        migrations.AlterModelOptions(
            name='niveau',
            options={'verbose_name': 'Niveau'},
        ),
        migrations.AlterModelOptions(
            name='runparam',
            options={'verbose_name': 'RunParam'},
        ),
        migrations.RemoveField(
            model_name='grade',
            name='status',
        ),
        migrations.RemoveField(
            model_name='niveau',
            name='groupes',
        ),
        migrations.AddField(
            model_name='professeur',
            name='status',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
