# Generated by Django 4.2.4 on 2023-08-23 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delta', '0002_alter_batiment_options_alter_cours_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupe',
            name='professeurs',
            field=models.ManyToManyField(blank=True, null=True, related_name='groupes_associes', to='delta.professeur'),
        ),
        migrations.AddField(
            model_name='professeur',
            name='groupes',
            field=models.ManyToManyField(blank=True, null=True, related_name='professeurs_associes', to='delta.groupe'),
        ),
    ]
