# Generated by Django 4.2.4 on 2023-08-20 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delta', '0003_alter_duree_options_alter_matiere_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professeur',
            name='cycle',
        ),
    ]
